TECH_KEYWORDS = [
    "fujifilm", "sony", "gfx", "canon", "nikon", "hasselblad", "leica",
    "phase one", "panasonic", "lumix", "blackmagic", "red digital",
    "red komodo", "insta360", "olympus", "om system", "ricoh", "pentax",
    "mamiya", "contax", "kodak", "ilford", "dji", "apple", "macbook",
    "mac", "iphone", "viltrox", "sigma", "tamron", "samyang", "zeiss",
    "sirui", "laowa", "rokinon", "voigtlander", "tokina", "7artisans",
    "ttartisan", "cooke", "angenieux", "arri", "fujinon", "nikkor",
    "zuiko", "godox", "aputure", "nanlite", "nanlux", "profoto",
    "elinchrom", "broncolor", "westcott", "smallrig", "feelworld",
    "portkeys", "atomos", "ninja v", "v-mount", "gold mount", "np-f",
    "manfrotto", "gitzo", "benro", "sachtler", "miller", "libec",
    "ronin", "zhiyun", "crane", "feiyutech", "edelkrone", "rhino slider",
    "tilta", "peak design", "think tank", "shimoda", "rode", "sennheiser",
    "zoom", "tascam", "saramonic", "hollyland", "comica", "shure",
    "lav mic", "boom", "xlr", "phantom power", "wireless go", "kamera",
    "camera", "lens", "mercek", "sensor", "sensör", "raw", "shutter",
    "enstantane", "ışık", "light", "lighting", "color", "renk",
    "grading", "lut", "arka plan", "background", "backstage", "kulis",
    "çekim", "shoot", "production", "prodüksiyon", "workflow", "iş akışı",
    "yapay zeka", "proart", "vlog", "cinematic", "sinematik",
    "photographer", "videographer", "bokeh", "log", "f-log", "s-log",
    "c-log", "prores", "braw", "anamorphic", "histogram", "zebra",
    "nd filter", "slog", "flog", "flog2", "flog2c", "slog1", "slog2",
    "slog3", "nlog", "logc", "makine", "vizör", "odak", "fiyat",
    "diyafram", "noise", "batarya", "mm", "iso", "gövde", "body",
    "x-t5", "x-s20", "x100", "x-h2", "eterna", "fotoğraf", "video",
    "sinematografi", "davinci resolve", "final cut", "premiere"
]
